### ISSUE TITLE
Error when used with `memoise`

### ISSUE THREAD

**Issue by rorynolan** [r-lib/conflicted#45]
I can't really tell what's going on here, but I'm getting an error about `setdiff()` when I haven't used it at all. 

``` r
library(conflicted)
library(tidyverse)
library(lubridate)
library(memoise)

tib <- tibble(x = 1:2, y = 3:4)

f <- function(tib) {
  mutate(tib, z = if_else(x == 1, y, x))
}
mf <- memoise(f)

f(tib)
#> # A tibble: 2 x 3
#>       x     y     z
#>   <int> <int> <int>
#> 1     1     3     3
#> 2     2     4     2

mf(tib)
#> [conflicted] `setdiff` found in 2 packages.
#> Either pick the one you want with `::` 
#> * lubridate::setdiff
#> * dplyr::setdiff
#> Or declare a preference with `conflict_prefer()`
#> * conflict_prefer("setdiff", "lubridate")
#> * conflict_prefer("setdiff", "dplyr")
```

<sup>Created on 2019-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by GegznaV** [comment]
I also faced a similar issue, when I had to resolve a conflict related to `setdiff()`, when I did not use it. But I think @rorynolan's example is reproducible enough.

Furthermore, this issue seems to be related: #44

**Comment by moodymudskipper** [comment]
You are using `setdiff` because it's part of the body of `mf` (check `body(mf)`) and `mf` is not namespaced so the use of setdiff is indeed ambiguous.

It might be a `memoise` issue, and maybe we should use the `::` notation everywhere or use masks in the definition of manufactured functions, this won't help with overloaded operators though.

We can fix this specific case by substituting `setdiff` with `base::setdiff` in the manufacture function's body.

``` r
library(conflicted)
library(tidyverse)
library(lubridate)
library(memoise)

tib <- tibble(x = 1:2, y = 3:4)

f <- function(tib) {
  mutate(tib, z = if_else(x == 1, y, x))
}
mf <- memoise(f)
body(mf) <- do.call(substitute, list(body(mf), list(setdiff = quote(base::setdiff))))
class(mf) <- c("memoised", "function") # seems that `body<-` strips off the class :(

f(tib)
#> # A tibble: 2 x 3
#>       x     y     z
#>   <int> <int> <int>
#> 1     1     3     3
#> 2     2     4     2

mf(tib)
#> # A tibble: 2 x 3
#>       x     y     z
#>   <int> <int> <int>
#> 1     1     3     3
#> 2     2     4     2
```

<sup>Created on 2019-11-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
